prueba/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='inicio'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/usuarios/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^crear/', views.PerfilUsuarioCreateView.as_view(), name='crear'),
    url(r'^editar/(?P<pk>\d+)', views.PerfilUsuarioUpdateView.as_view(), name='editar'),
    url(r'^listar', views.PerfilUsuarioListView.as_view(), name='listar'),
]

prueba/usuarios/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.conf import settings
from django.urls import reverse

from usuarios.managers import PerfilUsuarioManager


class PerfilUsuario(AbstractBaseUser, PermissionsMixin):

    foto = models.ImageField(upload_to='fotos', blank=True, null=True)
    email = models.EmailField(unique=True, verbose_name='Correo')
    first_name = models.CharField(max_length=30, verbose_name='Nombres')
    last_name = models.CharField(max_length=30, verbose_name='Apellidos')
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = PerfilUsuarioManager()

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método para obtener el nombre completo de un usuario, requerido por AbstractBaseUser
        :return: nombres y apellidos acompañados de un espacio
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método para obtener el nombre corto de un usuario, requerido por AbstractBaseUser
        :return: nombres
        """
        return self.first_name

    def guess_display_name(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método utilizado para mostrar el nombre de un usuario o agregar 'Tu'. Especialmente util en las templates cuando
        el usuario aún no ha especificado sus nombres y apellidos en la aplicación
        :return: nombre completo del usuario o el string 'Tu'
        """
        if self.get_full_name():
            dn = self.get_full_name()
        else:
            dn = "Tu"
        dn = dn.strip()
        return dn

    def get_img_url(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método que retorna la foto de perfil del sistema del usuario o un comodín en el caso de no tener foto
        :return: foto del usuario
        """
        if self.foto:
            return self.foto.url
        else:
            return settings.STATIC_URL + "img/no-user.png"

    def get_absolute_url(self):
        """
        Autor: Daniel Lopez
        Fecha: 26 agosto 2017
        Método para retornar una url despues de un cambio en una vista del modelo
        :return: URL
        """
        return reverse('usuarios:listar')

    def __str__(self):
        return self.guess_display_name()

prueba/usuarios/forms.py
from django import forms

from .models import PerfilUsuario


class CrearPerfilUsuarioForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CrearPerfilUsuarioForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.PasswordInput()

    class Meta:
        model = PerfilUsuario
        fields = ('foto', 'first_name', 'last_name', 'email', 'password')


class ActualizarPerfilUsuarioForm(forms.ModelForm):

    class Meta:
        model = PerfilUsuario
        fields = ('foto',  'first_name', 'last_name', 'email')

prueba/usuarios/views.py
from django.views.generic import CreateView, ListView, UpdateView

from usuarios.mixins import MessageMixin
from .models import PerfilUsuario
from .forms import CrearPerfilUsuarioForm, ActualizarPerfilUsuarioForm


class PerfilUsuarioCreateView(CreateView, MessageMixin):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para la creación de usuarios
    """
    model = PerfilUsuario
    form_class = CrearPerfilUsuarioForm
    mensaje_exito = "Usuario creado exitosamente"

    def form_valid(self, form):
        formulario = form.save(commit=False)
        formulario.set_password(formulario.password)
        form.save()
        return super(PerfilUsuarioCreateView, self).form_valid(form)


class PerfilUsuarioListView(ListView):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para listar de usuarios
    """
    model = PerfilUsuario


class PerfilUsuarioUpdateView(UpdateView, MessageMixin):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para la edición de usuarios
    """
    model = PerfilUsuario
    form_class = ActualizarPerfilUsuarioForm
    mensaje_exito = "Usuario editado exitosamente"

prueba/templates/usuarios/perfilusuario_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titulo_pagina %}
    Detalles usuario
{% endblock titulo_pagina %}

{% block titulo_seccion %}
    Detalles usuario
{% endblock titulo_seccion %}

{% block titulo_panel %}
    Detalles usuario
{% endblock titulo_panel %}

{% block contenido_panel %}
    <div class="row">
        <div class="col-lg-12">
            <div class="m-b-md">
                <a class="btn btn-success btn-md pull-right" href="{% url 'gestion_usuarios:listar' %}"><i class="fa fa-arrow-left"></i> Regresar </a>
                <h2>{{ object.get_full_name }}</h2>
            </div>
        </div>
        <div class="col-md-12 ">
            <div class="col-md-2 text-center">
                <img src="{{ object.get_img_url }}" class="img-responsive img-thumbnail" >
            </div>
            <div class="col-md-5 ">
                <dl class="dl-horizontal ">

                    <dt>Nombre:</dt> <dd>{{ object.first_name }}</dd>
                    <dt>Apellidos:</dt> <dd>{{ object.last_name }}</dd>
                    <dt>Nombre usuario:</dt> <dd>{{ object.username}}</dd>
                    <dt>Tipo usuario:</dt> <dd>{{ object.get_tipo_usuario_display }}</dd>
                    <dt>Tipo Identificación:</dt> <dd>{{ object.get_tipo_id_display }}</dd>
                    <dt>Identificación:</dt> <dd>{{ object.identificacion }}</dd>
                </dl>
            </div>
            <div class="col-md-5">
                <dl class="dl-horizontal">
                    <dt>Correo electrónico:</dt> <dd>{{ object.email }}</dd>
                    <dt>Fecha de nacimiento:</dt> <dd>{{ object.fecha_nacimiento }}</dd>
                    <dt>Último acceso al sistema:</dt> <dd>{% if perfilusuario.last_login  %}{{ perfilusuario.last_login }}{% else %}Nunca ha accedido{% endif %}</dd>
                </dl>
            </div>
        </div>
    </div>
{% endblock contenido_panel %}

prueba/templates/usuarios/perfilusuario_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo_pagina %}
    {% if object %}Editar{% else %}Registrar{% endif %} Usuario
{% endblock titulo_pagina %}

{% block titulo_seccion %}
    {% if object %}Editar{% else %}Registrar{% endif %} Usuario
{% endblock titulo_seccion %}

{% block titulo_panel %}
    {% if object %}Editar{% else %}Registrar{% endif %} Usuario
{% endblock titulo_panel %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'plugins/chosen/chosen.min.css' %}">
{% endblock css %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'plugins/chosen/chosen.jquery.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/validaciones/validacion-tecnico.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/validaciones/gestion_usuarios/validaciones-usuarios-form.js'%}"></script>
{% endblock javascript %}

{% block contenido_panel %}    
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form method="POST" class="form-horizontal" enctype="multipart/form-data" id="usuario-form">{% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary"%}
                </div>
            </form>
        </div>
    </div>
{% endblock contenido_panel %}

prueba/templates/usuarios/perfilusuario_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titulo_pagina %}
    Listar Usuarios
{% endblock titulo_pagina %}

{% block titulo_seccion %}
{% endblock titulo_seccion %}

{% block titulo_panel %}
    Listar Usuarios
{% endblock titulo_panel %}

{% block contenido_pagina %}
<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Usuarios registrados</h4>
            </div>
            <div class="panel-body">
                <div style="padding-bottom: 15px; padding-right: 15px;" class="row">
                    <div class="pull-right">
                        <a href="{% url 'usuarios:crear' %}" class="btn btn-primary"> Crear usuario</a>
                    </div>
                </div>
                <table id="data-table" class="table dataTable table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Fecha de ingreso</th>
                            <th>Email</th>
                            <th>Staff</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr class="gradeU">
                            <td>{{ object.get_full_name }}</td>
                            <td>{{ object.date_joined }}</td>
                            <td>{{ object.email }}</td>
                            <td>{% if object.is_staff %} SI {% else %} NO {% endif %}</td>
                            <td>
                                <div class="btn-group m-r-5 m-b-5">
								<a href="javascript:;" class="btn btn-success">Opciones</a>
								<a href="javascript:;" data-toggle="dropdown" class="btn btn-success dropdown-toggle">
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu pull-right">
									<li><a href="{% url 'usuarios:editar' object.id %}"><i class="fa fa-edit text-primary"></i> Editar</a></li>
								</ul>
							</div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
{% endblock contenido_pagina %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/personalizado/tabla-listar-usuarios.js' %}"></script>
{% endblock javascript %}