prueba/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='inicio'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/recursos/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^crear/$', views.RecursoCreateView.as_view(), name='crear'),
    url(r'^editar/(?P<pk>\d+)$', views.RecursoUpdateView.as_view(), name='editar'),
    url(r'^listar$', views.RecursosListView.as_view(), name='listar'),
    url(r'^mis-recursos$', views.MisRecursosAsignadosListView.as_view(), name='mis_recursos'),
    url(r'^crear-asignacion/(?P<pk>\d+)$', views.RecursoAsignadoCreateView.as_view(), name='crear_asignacion'),
    url(r'^historial-asignaciones$', views.HistorialRecursosListView.as_view(), name='historial_asignaciones'),
    url(r'^transferir-recurso/(?P<pk>\d+)$', views.TransferirRecursoFormView.as_view(), name='transferir_recurso'),

]

prueba/recursos/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from .managers import RecursoAsignadoManager
from usuarios.models import PerfilUsuario


class Recurso(models.Model):

    nombre = models.CharField(max_length=50)
    categoria = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)
    serie = models.CharField(max_length=50)
    cantidad = models.IntegerField(validators=[MinValueValidator(0)])

    def restar_cantidad(self, cantidad):
        """
        Autor: Daniel Lopez
        Fecha: 26 agosto 2017
        Método para restar cantidades a un recurso
        :param cantidad: cantidad a restar
        """
        self.cantidad -= cantidad
        self.save()

    def get_absolute_url(self):
        return reverse("recursos:listar")

    def __str__(self):
        return self.nombre


class RecursoAsignado(models.Model):

    recurso = models.ForeignKey(Recurso)
    usuario = models.ForeignKey(PerfilUsuario)
    cantidad = models.IntegerField()
    fecha = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    custom_objects = RecursoAsignadoManager()

    def sumar_cantidad_recurso(self, cantidad):
        """
        Autor: Daniel Lopez
        Fecha: 26 Agosto 2017
        Método para sumar una cantidad a una asignación
        :param cantidad: cantidad a sumar
        """
        self.cantidad += cantidad
        self.save()

    def restar_cantidad_recurso(self, cantidad):
        """
        Autor: Daniel Lopez
        Fecha: 26 Agosto 2017
        Método para restar una cantidad a una asignación
        :param cantidad: cantidad a restar
        """
        self.cantidad -= cantidad
        self.save()

    def get_absolute_url(self):
        return reverse("recursos:historial_asignaciones")

    def __str__(self):
        return "Se le asigno {} de {} a {}".format(self.cantidad, self.recurso, self.usuario)


class HistorialRecursos(models.Model):

    recurso = models.ForeignKey(Recurso)
    fuente = models.ForeignKey(PerfilUsuario, related_name="Fuente", null=True)
    remitente = models.ForeignKey(PerfilUsuario, related_name='remitente')
    destinatario = models.ForeignKey(PerfilUsuario, related_name='destinatario')
    cantidad = models.IntegerField()
    fecha = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Se trasladaron ({}) {} el dia {}, desde {} a {} ".format(self.cantidad, self.recurso, self.fecha,
                                                                         self.remitente, self.destinatario)

prueba/recursos/forms.py
from django import forms

from usuarios.models import PerfilUsuario
from .models import Recurso, RecursoAsignado


class RecursoForm(forms.ModelForm):

    class Meta:
        model = Recurso
        fields = ('nombre', 'categoria', 'marca', 'serie', 'cantidad')


class RecursoAsignadoForm(forms.ModelForm):

    def __init__(self, usuario, recurso, *args, **kwargs):
        super(RecursoAsignadoForm, self).__init__(*args, **kwargs)
        self.recurso = recurso
        self.fields['recurso'].initial = recurso
        self.fields['recurso'].widget.attrs['readonly'] = True
        self.fields['usuario'].queryset = PerfilUsuario.objects.get_demas_usuarios(usuario)

    def clean_cantidad(self):
        """
        Autor: Daniel Lopez
        Fecha: 26 agosto 2017
        Método para verificar que el almacen tiene suficiente cantidad de un recurso para asignar un usuario
        :return: cantidad a transferir si tiene suficiente, error de lo contrario
        """
        recurso = self.cleaned_data['recurso']
        cantidad = self.cleaned_data['cantidad']

        total = recurso.cantidad - cantidad

        if total < 0:
            self.add_error('cantidad', 'No hay suficientes recursos')

        return cantidad

    class Meta:
        model = RecursoAsignado
        fields = ('recurso',  'usuario', 'cantidad')


class TransferenciaRecursosForm(forms.ModelForm):

    def __init__(self, usuario, asignacion, *args, **kwargs):
        super(TransferenciaRecursosForm, self).__init__(*args, **kwargs)
        self.asignacion = asignacion
        self.fields['recurso'].initial = asignacion.recurso
        self.fields['recurso'].widget.attrs['readonly'] = True
        self.fields['usuario'].queryset = PerfilUsuario.objects.get_demas_usuarios(usuario)

    def clean_cantidad(self):
        """
        Autor: Daniel Lopez
        Fecha: 26 agosto 2017
        Método para verificar que el usuario tiene suficiente cantidad de un recurso para asignar a otro
        :return: cantidad a transferir si tiene suficiente, error de lo contrario
        """

        cantidad = self.cleaned_data['cantidad']
        resta = self.asignacion.cantidad - cantidad
        if resta < 0:
            self.add_error('cantidad', 'No tiene suficiente cantidad del recurso para hacer la transferencia')
        return cantidad

    class Meta:
        model = RecursoAsignado
        fields = ('recurso',  'usuario', 'cantidad')

prueba/recursos/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView

from .models import Recurso, RecursoAsignado, HistorialRecursos
from .forms import RecursoForm, RecursoAsignadoForm, TransferenciaRecursosForm


class RecursoCreateView(LoginRequiredMixin, CreateView):
    """
    Vista para crear recursos
    """
    model = Recurso
    form_class = RecursoForm
    raise_exception = True


class RecursosListView(LoginRequiredMixin, ListView):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para ver los recursos sin asignar
    """
    model = Recurso
    raise_exception = True


class MisRecursosAsignadosListView(LoginRequiredMixin, ListView):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para ver los recursos que tengo asignados
    """
    model = RecursoAsignado
    raise_exception = True

    def get_queryset(self):
        return self.model.custom_objects.get_asignaciones_user(self.request.user)


class RecursoUpdateView(LoginRequiredMixin, UpdateView):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para editar recursos del almacen
    """
    model = Recurso
    form_class = RecursoForm
    success_msg = "Contacto editado"
    raise_exception = True


class RecursoAsignadoCreateView(LoginRequiredMixin, CreateView):
    """
    Autor: Daniel Lopez
    Fecha: 26 Agosto 2017
    Vista para la asignación de recursos a un usuario desde el almacen, se verifica que los recursos existan y
    se guarda la transaccción en el historial
    """
    model = RecursoAsignado
    raise_exception = True
    form_class = RecursoAsignadoForm
    mensaje_exito = "Se realizo la transferencia exitosamente"

    def dispatch(self, request, *args, **kwargs):
        self.recurso = Recurso.objects.get(id=self.kwargs['pk'])
        return super(RecursoAsignadoCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        recurso = form.cleaned_data['recurso']
        cantidad = form.cleaned_data['cantidad']
        usuario = form.cleaned_data['usuario']

        recurso.restar_cantidad(cantidad)

        # Se crea un registro en el historial con el cambio de recursos de el almacen al usuario
        HistorialRecursos.objects.create(recurso=form.instance.recurso,
                                         remitente=self.request.user,
                                         destinatario=form.instance.usuario,
                                         cantidad=form.instance.cantidad)

        asignacion = self.model.custom_objects.get_recurso_si_existe_por_usuario(recurso, usuario)

        # Se verifica que si el usuario tiene una asignación del mismo recurso de ser así se suma
        if asignacion:
            asignacion.sumar_cantidad_recurso(cantidad)
            messages.success(self.request, self.mensaje_exito)
            return redirect(self.get_success_url())

        return super(RecursoAsignadoCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(RecursoAsignadoCreateView, self).get_form_kwargs()
        kwargs['usuario'] = self.request.user
        kwargs['recurso'] = self.recurso
        return kwargs

    def get_success_url(self):
        return reverse('recursos:historial_asignaciones')


class TransferirRecursoFormView(LoginRequiredMixin, CreateView):
    """
    Autor: Daniel Lopez
    Fecha: 26 agosto 2017
    Vista para transferir recursos de un usuario a otro
    """

    model = RecursoAsignado
    form_class = TransferenciaRecursosForm
    mensaje_exito = "Se realizo la transferencia exitosamente"
    raise_exception = True

    def dispatch(self, request, *args, **kwargs):
        self.asignacion = RecursoAsignado.objects.get(id=self.kwargs['pk'])
        return super(TransferirRecursoFormView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(TransferirRecursoFormView, self).get_form_kwargs()
        kwargs['usuario'] = self.request.user
        kwargs['asignacion'] = self.asignacion
        return kwargs

    def form_valid(self, form):

        recurso = form.cleaned_data['recurso']
        cantidad = form.cleaned_data['cantidad']
        usuario = form.cleaned_data['usuario']

        self.asignacion.restar_cantidad_recurso(cantidad)

        # Se crea un registro en el historial con el cambio de recursos entre usuarios
        HistorialRecursos.objects.create(recurso=self.asignacion.recurso,
                                         fuente=self.asignacion.usuario,
                                         remitente=self.request.user,
                                         destinatario=form.instance.usuario,
                                         cantidad=form.instance.cantidad)

        asignacion = self.model.custom_objects.get_recurso_si_existe_por_usuario(recurso, usuario)

        # Se verifica que si el usuario tiene una asignación del mismo recurso de ser así se suma
        if asignacion:
            asignacion.sumar_cantidad_recurso(cantidad)
            messages.success(self.request, self.mensaje_exito)
            return redirect(self.get_success_url())

        return super(TransferirRecursoFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('recursos:historial_asignaciones')


class HistorialRecursosListView(LoginRequiredMixin, ListView):
    """
    Autor: Daniel Lopez
    Fecha: 26 Agosto 2017
    Vista para ver el historial de movimientos de los recursos
    """
    model = HistorialRecursos
    raise_exception = True

prueba/templates/recursos/historialrecursos_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titulo_pagina %}
    Historial transferencia
{% endblock titulo_pagina %}

{% block titulo_seccion %}
{% endblock titulo_seccion %}

{% block titulo_panel %}
    Historial transferencia
{% endblock titulo_panel %}

{% block contenido_pagina %}
<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Historial de transferencia de recursos</h4>
            </div>
            <div class="panel-body">
                <table id="data-table" class="table dataTable table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Fuente</th>
                            <th>recurso</th>
                            <th>remitente</th>
                            <th>destinatario</th>
                            <th>Cantidad</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr class="gradeU">
                            <td>{{ object.fecha|date:'Y-m-d H:i:s'}}</td>
                            <td>{% if object.fuente %} {{ object.fuente }} {% else %} ALMACEN {% endif %}</td>
                            <td>{{ object.recurso }}</td>
                            <td>{{ object.remitente }}</td>
                            <td>{{ object.destinatario }}</td>
                            <td>{{ object.cantidad }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
{% endblock contenido_pagina %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/personalizado/tabla-listar-usuarios.js' %}"></script>
{% endblock javascript %}

prueba/templates/recursos/recurso_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo_pagina %}
    {% if object %}Editar{% else %}Registrar{% endif %} Recurso
{% endblock titulo_pagina %}

{% block titulo_seccion %}
    {% if object %}Editar{% else %}Registrar{% endif %} Recurso
{% endblock titulo_seccion %}

{% block titulo_panel %}
    {% if object %}Editar{% else %}Registrar{% endif %} Recurso
{% endblock titulo_panel %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'plugins/chosen/chosen.min.css' %}">
{% endblock css %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'plugins/chosen/chosen.jquery.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/validaciones/validacion-tecnico.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/validaciones/gestion_usuarios/validaciones-usuarios-form.js'%}"></script>
{% endblock javascript %}

{% block contenido_panel %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form method="POST" class="form-horizontal" enctype="multipart/form-data" id="usuario-form">{% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary"%}
                </div>
            </form>
        </div>
    </div>
{% endblock contenido_panel %}

prueba/templates/recursos/recurso_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titulo_pagina %}
    Listar Recursos
{% endblock titulo_pagina %}

{% block titulo_seccion %}
{% endblock titulo_seccion %}

{% block titulo_panel %}
    Listar Recursos
{% endblock titulo_panel %}

{% block contenido_pagina %}
<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Recursos registrados</h4>
            </div>
            <div class="panel-body">
                <div style="padding-bottom: 15px; padding-right: 15px;" class="row">
                    <div class="pull-right">
                        <a href="{% url 'recursos:crear' %}" class="btn btn-primary"> Agregar recurso</a>
                    </div>
                </div>
                <table id="data-table" class="table dataTable table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Categoria</th>
                            <th>Marca</th>
                            <th>Serie</th>
                            <th>Cantidad</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr class="gradeU">
                            <td>{{ object.nombre }}</td>
                            <td>{{ object.categoria }}</td>
                            <td>{{ object.marca }}</td>
                            <td>{{ object.serie }}</td>
                            <td>{{ object.cantidad }}</td>
                            <td>
                                <div class="btn-group m-r-5 m-b-5">
								<a href="javascript:;" class="btn btn-success">Opciones</a>
								<a href="javascript:;" data-toggle="dropdown" class="btn btn-success dropdown-toggle">
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu pull-right">
									<li><a href="{% url 'recursos:editar' object.id %}"><i class="fa fa-edit text-primary"></i> Editar</a></li>
									<li><a href="{% url 'recursos:crear_asignacion' object.id %}"><i class="fa fa-send text-success"></i> Transferir recursos</a></li>
								</ul>
							</div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
{% endblock contenido_pagina %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/personalizado/tabla-listar-usuarios.js' %}"></script>
{% endblock javascript %}

prueba/templates/recursos/recursoasignado_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo_pagina %}
    {% if object %}Editar{% else %}Registrar{% endif %} Recurso
{% endblock titulo_pagina %}

{% block titulo_seccion %}
    {% if object %}Editar{% else %}Registrar{% endif %} Recurso
{% endblock titulo_seccion %}

{% block titulo_panel %}
    {% if object %}Editar{% else %}Registrar{% endif %} Recurso
{% endblock titulo_panel %}

{% block css %}
    <link type="text/css" rel="stylesheet" href="{% static 'plugins/chosen/chosen.min.css' %}">
{% endblock css %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'plugins/chosen/chosen.jquery.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/validaciones/validacion-tecnico.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/validaciones/gestion_usuarios/validaciones-usuarios-form.js'%}"></script>
{% endblock javascript %}

{% block contenido_panel %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form method="POST" class="form-horizontal" enctype="multipart/form-data" id="usuario-form">{% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    {% bootstrap_button "Guardar" button_type="submit" button_class="btn-primary"%}
                </div>
            </form>
        </div>
    </div>
{% endblock contenido_panel %}

prueba/templates/recursos/recursoasignado_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block titulo_pagina %}
    Listar Recursos
{% endblock titulo_pagina %}

{% block titulo_seccion %}
{% endblock titulo_seccion %}

{% block titulo_panel %}
    Listar Recursos
{% endblock titulo_panel %}

{% block contenido_pagina %}
<!-- begin row -->
<div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title">Recursos registrados</h4>
            </div>
            <div class="panel-body">
                <table id="data-table" class="table dataTable table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Recurso</th>
                            <th>Usuario</th>
                            <th>Cantidad</th>
                            <th>Fecha de asignacion</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                        <tr class="gradeU">
                            <td>{{ object.recurso }}</td>
                            <td>{{ object.usuario }}</td>
                            <td>{{ object.cantidad }}</td>
                            <td>{{ object.fecha }}</td>
                            <td>
                                <div class="btn-group m-r-5 m-b-5">
								<a href="javascript:;" class="btn btn-success">Opciones</a>
								<a href="javascript:;" data-toggle="dropdown" class="btn btn-success dropdown-toggle">
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu pull-right">
									<li><a href="{% url 'recursos:transferir_recurso' object.id %}"><i class="fa fa-send text-success"></i> Transferir recursos</a></li>
								</ul>
							</div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
{% endblock contenido_pagina %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/plugins/dataTables/datatables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/personalizado/tabla-listar-usuarios.js' %}"></script>
{% endblock javascript %}