prueba/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='base.html'), name='inicio'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^usuarios/', include('usuarios.urls', namespace='usuarios')),
    url(r'^recursos/', include('recursos.urls', namespace='recursos')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prueba/recursos/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^crear/$', views.RecursoCreateView.as_view(), name='crear'),
    url(r'^editar/(?P<pk>\d+)$', views.RecursoUpdateView.as_view(), name='editar'),
    url(r'^listar$', views.RecursosListView.as_view(), name='listar'),
    url(r'^mis-recursos$', views.MisRecursosAsignadosListView.as_view(), name='mis_recursos'),
    url(r'^crear-asignacion/(?P<pk>\d+)$', views.RecursoAsignadoCreateView.as_view(), name='crear_asignacion'),
    url(r'^historial-asignaciones$', views.HistorialRecursosListView.as_view(), name='historial_asignaciones'),
    url(r'^transferir-recurso/(?P<pk>\d+)$', views.TransferirRecursoFormView.as_view(), name='transferir_recurso'),

]

prueba/usuarios/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.conf import settings
from django.urls import reverse

from usuarios.managers import PerfilUsuarioManager


class PerfilUsuario(AbstractBaseUser, PermissionsMixin):

    foto = models.ImageField(upload_to='fotos', blank=True, null=True)
    email = models.EmailField(unique=True, verbose_name='Correo')
    first_name = models.CharField(max_length=30, verbose_name='Nombres')
    last_name = models.CharField(max_length=30, verbose_name='Apellidos')
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = PerfilUsuarioManager()

    USERNAME_FIELD = 'email'

    def get_full_name(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método para obtener el nombre completo de un usuario, requerido por AbstractBaseUser
        :return: nombres y apellidos acompañados de un espacio
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método para obtener el nombre corto de un usuario, requerido por AbstractBaseUser
        :return: nombres
        """
        return self.first_name

    def guess_display_name(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método utilizado para mostrar el nombre de un usuario o agregar 'Tu'. Especialmente util en las templates cuando
        el usuario aún no ha especificado sus nombres y apellidos en la aplicación
        :return: nombre completo del usuario o el string 'Tu'
        """
        if self.get_full_name():
            dn = self.get_full_name()
        else:
            dn = "Tu"
        dn = dn.strip()
        return dn

    def get_img_url(self):
        """
        Autor: Daniel Lopes
        Fecha: 26 Agosto 2017
        Método que retorna la foto de perfil del sistema del usuario o un comodín en el caso de no tener foto
        :return: foto del usuario
        """
        if self.foto:
            return self.foto.url
        else:
            return settings.STATIC_URL + "img/no-user.png"

    def get_absolute_url(self):
        """
        Autor: Daniel Lopez
        Fecha: 26 agosto 2017
        Método para retornar una url despues de un cambio en una vista del modelo
        :return: URL
        """
        return reverse('usuarios:listar')

    def __str__(self):
        return self.guess_display_name()

prueba/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
	{% block meta %}
    {% endblock %}
	<meta charset="utf-8" />
	<title>{% block titulo_pagina %} {{ titulo_html_empresa }} {% endblock titulo_pagina %}</title>
	<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
	<meta content="" name="description" />
	<meta content="prueba" name="author" />

    <script src="{% static 'plugins/jquery/jquery-1.9.1.min.js' %}"></script>
	<script src="{% static 'plugins/jquery-ui/ui/minified/jquery-ui.min.js' %}"></script>
	<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/jquery/jquery-migrate-1.1.0.min.js' %}"></script>

	<!-- ================== BEGIN BASE CSS STYLE ================== -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,100italic,300,300italic,400,400italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" type="text/css" />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link href="{% static 'plugins/jquery-ui/themes/base/minified/jquery-ui.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/bootstrap-datepicker/css/datepicker3.css' %}" rel="stylesheet" />
    <link href="{% static 'css/plugins/dataTables/datatables.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/animate.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/style-responsive.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/theme/blue.css' %}" rel="stylesheet" id="theme" />
    <link href="{% static 'css/plugins/toastr/toastr.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/personal.css' %}" rel="stylesheet">
    <link href="{% static 'css/select2.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
    <style>
        [readonly="1"]{
            pointer-events: none;
        }
        .select2 {
            width: 100% !important;
        }
        @media only screen and (min-width: 768px) {
            h2{
                font-size: 3em;
            }
        }
        @media only screen and (max-width: 380px) {
            h2{
                font-size: 1em;
            }
        }
    </style>

    {{ form.media }}

    {% block css %}
    {% endblock %}

	<!-- ================== END BASE CSS STYLE ================== -->

    <!-- ================== BEGIN BASE JS ================== -->
	<script src="{% static 'plugins/pace/pace.min.js' %}"></script>

	<!-- ================== END BASE JS ================== -->

</head>
<body>
	<!-- begin #page-loader -->
	<div id="page-loader">
	    <div class="material-loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
            </svg>
            <div class="message">Cargando...</div>
        </div>
	</div>
	<!-- end #page-loader -->
	
	<!-- begin #page-container -->
	<div id="page-container" class="fade page-sidebar-fixed page-header-fixed page-with-wide-sidebar">
		<!-- begin #header -->
		<div id="header" class="header navbar navbar-default navbar-fixed-top">
			<!-- begin container-fluid -->
			<div class="container-fluid">
				<!-- begin mobile sidebar expand / collapse button -->
				<div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed navbar-toggle-left" data-click="sidebar-minify">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
					<button type="button" class="navbar-toggle" data-click="sidebar-toggled">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="{% url 'inicio' %}" class="navbar-brand">
                        Gestion de inventario
					</a>
				</div>
				<!-- end mobile sidebar expand / collapse button -->
				
				<!-- begin header navigation right -->
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
						<li class="dropdown navbar-user">
							<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
								<img src="{{ user.get_img_url }} " alt="" />
								<span class="hidden-xs">{{ user.get_full_name}}</span>
							</a>
							<ul class="dropdown-menu animated fadeInLeft">
								<li class="arrow"></li>
                                {% if usuario %}
                                    {% if perms.gestion_usuarios.change_perfilusuario %}
								    <li><a href="{% url 'usuarios:editar' usuario.id %}">Editar mi perfil</a></li>
                                    {% endif %}
                                {% endif %}
								<li><a href="{% url 'password_change' %}">Cambiar Contraseña</a></li>
								<li class="divider"></li>
								<li><a href="{% url 'logout' %}">Cerrar Sesión</a></li>
							</ul>
						</li>
					{% else %}
						<li>
	                        <div class="p-t-10 p-r-20">
	                            <a href="{% url 'login' %}" class="btn btn-primary btn-sm">
	                                <i class="fa fa-key"></i> Iniciar Sesión
	                            </a>
	                        </div>
	                    </li>
					{% endif %}
				</ul>
				<!-- end header navigation right -->				
			</div>
			<!-- end container-fluid -->
		</div>
		<!-- end #header -->
		
		<!-- begin #sidebar -->
		<div id="sidebar" class="sidebar sidebar-grid">
			<!-- begin sidebar scrollbar -->
			<div data-scrollbar="true" data-height="100%">

                {% if user.is_authenticated %}
				<!-- begin sidebar user -->
				<ul class="nav">
					<li class="nav-profile">
					    <a href="#" data-toggle="nav-profile">
                            <div class="image">
                                <img src="{{ user.get_img_url }}" alt="" />
                            </div>
                            <div class="info">
                                {{ user.get_full_name }}
                                <small>Usuario de inventario</small>
                            </div>
						</a>
					</li>
				</ul>
				<!-- end sidebar user -->
                {% endif %}
				<!-- begin sidebar nav -->
				<ul class="nav">
					<li class="nav-header">Menú de opciones</li>
					{% include "menus/_base_menus.html" %}
			        <!-- begin sidebar minify button -->
					<li><a href="javascript:;" class="sidebar-minify-btn" data-click="sidebar-minify"><i class="fa fa-angle-double-left"></i></a></li>
			        <!-- end sidebar minify button -->
				</ul>
				<!-- end sidebar nav -->
			</div>
			<!-- end sidebar scrollbar -->
		</div>
		<div class="sidebar-bg"></div>
		<!-- end #sidebar -->
		
		<!-- begin #content -->
		<div id="content" class="content">
			<!-- begin page-header -->
			<h1 class="page-header">{% block titulo_seccion %}{% endblock titulo_seccion %}</h1>
			<!-- end page-header -->
			
			{% block contenido_pagina %}
				<div class="row">
				    <div class="col-md-12">
	                    <div class="panel panel-inverse">
	                        <div class="panel-heading">
	                            <div class="panel-heading-btn">
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
	                            </div>
                                    <h4 class="panel-title">{%block titulo_panel %} Mision {% endblock titulo_panel %}</h4>
	                        </div>
	                        <div class="panel-body">
	                            {% block contenido_panel %}
                                    <div class="col-md-12">
                                        <h3>Bienvenidos a la prueba para DELTEC</h3>
                                        <div class="col-md-12">
                                        </div>
                                    </div>
	                            {% endblock contenido_panel %}
	                        </div>
	                    </div>
				    </div>
				</div>
			{% endblock contenido_pagina %}
		</div>
		<!-- end #content -->
		<!-- begin scroll to top btn -->
		<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
		<!-- end scroll to top btn -->
	</div>
	<!-- end page container -->
	
	<!-- ================== BEGIN BASE JS ================== -->
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>

	<!--[if lt IE 9]>
		<script src="{% static 'crossbrowserjs/html5shiv.js' %}"></script>
		<script src="{% static 'crossbrowserjs/respond.min.js' %}"></script>
		<script src="{% static 'crossbrowserjs/excanvas.min.js' %}"></script>
	<![endif]-->
	<script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'plugins/jquery-cookie/jquery.cookie.js' %}"></script>
	<!-- ================== END BASE JS ================== -->
	
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'js/apps.min.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->

	<!-- ================== BEGIN CUSTOM JS ================== -->


    <script src="{% static 'plugins/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'plugins/select2/dist/js/i18n/es.js' %}"></script>

	<script src="{% static 'js/tooltip.js' %}"></script>
    <script>
    $(document).ready(function(){

        $.each($("span.help-block:not(.has-error span), div.help-block:not(.has-error div)"),function(){
            var bloqueActual = $(this);
            nuevoElemento = bloqueActual.siblings("label");
            nuevoElemento.after(" <span style='font-size:14px;color: #0044cc;'><i class='fa fa-question-circle add-tooltip' data-placement='right' data-toggle='tooltip' title='"+bloqueActual.text()+"'></i></span>");
            bloqueActual.remove();
        });

        $(".add-tooltip").tooltip();
    });
    </script>
    <script>
        var actualLanguage = 'es_ES';
        var dateFormat = "DD/MM/YYYY";
    </script>
	{# SCRIPT PARA EL MANEJO DE TOOLTIPS Y SELECTORES #}
	<script type="text/javascript">
        var base = "{{ STATIC_URL }}";
        function urlModal(link) {
                //Funcionalidad para agregar la url al modal
                var url = link.getAttribute("data-url");
                document.getElementById("confirmar-desactivate").setAttribute("href",url);
            }
        $(document).ready(function() {
            $('[data-toggle=tooltip]').tooltip();
            $("select.one").select2({width: '100%', multiple:false, language: "es"});
            $("select.many").select2({multiple:true, width: '100%', language: "es"});

        });
    </script>

	{# SCRIPT PARA EL MANEJO DE LOS MENSAJES EN EL SITE #}
	<script src="{% static 'js/plugins/toastr/toastr.min.js' %}"></script>
    <script>
        {% for msg in messages %}
            $(document).ready(function(){
                    setTimeout(function() {
                    toastr.options = {
                        "closeButton": true,
                        "progressBar": true,
                        "showEasing": "swing"
                    };
                    toastr["{{ msg.tags }}"]("{{msg}}")
                },500);

            });
        {% endfor %}
    </script>    
	{% block javascript %}
	{% endblock javascript %}
	<!-- ================== END CUSTOM JS ================== -->
	<script>

		$(document).ready(function() {
			App.init();
		});
	</script>
</body>
</html>